/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _protectedRouteImport } from './routes/__protected'
import { Route as _publicRouteImport } from './routes/__public'
import { Route as _protectedIndexRouteImport } from './routes/__protected/index'
import { Route as _publicSignInRouteImport } from './routes/__public/sign-in'

const _protectedRoute = _protectedRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicRoute = _publicRouteImport.update({
  id: '/__public',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedIndexRoute = _protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _protectedRoute,
} as any)
const _publicSignInRoute = _publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => _publicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _protectedIndexRoute
  '/sign-in': typeof _publicSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof _protectedIndexRoute
  '/sign-in': typeof _publicSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__protected': typeof _protectedRouteWithChildren
  '/__public': typeof _publicRouteWithChildren
  '/__public/sign-in': typeof _publicSignInRoute
  '/__protected/': typeof _protectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in'
  id:
    | '__root__'
    | '/__protected'
    | '/__public'
    | '/__public/sign-in'
    | '/__protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _protectedRoute: typeof _protectedRouteWithChildren
  _publicRoute: typeof _publicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _protectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public': {
      id: '/__public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _publicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/': {
      id: '/__protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _protectedIndexRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__public/sign-in': {
      id: '/__public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof _publicSignInRouteImport
      parentRoute: typeof _publicRoute
    }
  }
}

interface _protectedRouteChildren {
  _protectedIndexRoute: typeof _protectedIndexRoute
}

const _protectedRouteChildren: _protectedRouteChildren = {
  _protectedIndexRoute: _protectedIndexRoute,
}

const _protectedRouteWithChildren = _protectedRoute._addFileChildren(
  _protectedRouteChildren,
)

interface _publicRouteChildren {
  _publicSignInRoute: typeof _publicSignInRoute
}

const _publicRouteChildren: _publicRouteChildren = {
  _publicSignInRoute: _publicSignInRoute,
}

const _publicRouteWithChildren =
  _publicRoute._addFileChildren(_publicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _protectedRoute: _protectedRouteWithChildren,
  _publicRoute: _publicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
